/**
 * Real US state metadata (name/abbreviation/FIPS) and bounding box, derived once
 * from Census TIGER/Line boundary data (via us-atlas), courtesy of the nationwide
 * siting-advisor reference project (reference/nationwide-advisor). Generated by
 * .scratch/gen_states_directory.js — not hand-maintained.
 *
 * This is what lets src/states/registry.ts list all 50 states + DC with a real
 * name and a real map viewport to fly to, even though only Washington currently
 * has a live StateDefinition with layers/sources wired up.
 */
export interface StateDirectoryEntry {
  id: string;
  name: string;
  abbreviation: string;
  fips: string;
  bounds: [[number, number], [number, number]];
  center: [number, number];
}

export const US_STATES_DIRECTORY: StateDirectoryEntry[] = [
  {
    "id": "al",
    "name": "Alabama",
    "abbreviation": "AL",
    "fips": "01",
    "bounds": [
      [
        -88.475,
        30.223
      ],
      [
        -84.892,
        35.008
      ]
    ],
    "center": [
      -86.684,
      32.615
    ]
  },
  {
    "id": "ak",
    "name": "Alaska",
    "abbreviation": "AK",
    "fips": "02",
    "bounds": [
      [
        -179.137,
        51.229
      ],
      [
        179.775,
        71.353
      ]
    ],
    "center": [
      0.319,
      61.291
    ]
  },
  {
    "id": "az",
    "name": "Arizona",
    "abbreviation": "AZ",
    "fips": "04",
    "bounds": [
      [
        -114.813,
        31.332
      ],
      [
        -109.045,
        37.004
      ]
    ],
    "center": [
      -111.929,
      34.168
    ]
  },
  {
    "id": "ar",
    "name": "Arkansas",
    "abbreviation": "AR",
    "fips": "05",
    "bounds": [
      [
        -94.619,
        33.004
      ],
      [
        -89.655,
        36.5
      ]
    ],
    "center": [
      -92.137,
      34.752
    ]
  },
  {
    "id": "ca",
    "name": "California",
    "abbreviation": "CA",
    "fips": "06",
    "bounds": [
      [
        -124.411,
        32.534
      ],
      [
        -114.134,
        42.01
      ]
    ],
    "center": [
      -119.273,
      37.272
    ]
  },
  {
    "id": "co",
    "name": "Colorado",
    "abbreviation": "CO",
    "fips": "08",
    "bounds": [
      [
        -109.059,
        36.993
      ],
      [
        -102.042,
        41.002
      ]
    ],
    "center": [
      -105.551,
      38.997
    ]
  },
  {
    "id": "ct",
    "name": "Connecticut",
    "abbreviation": "CT",
    "fips": "09",
    "bounds": [
      [
        -73.726,
        40.985
      ],
      [
        -71.788,
        42.051
      ]
    ],
    "center": [
      -72.757,
      41.518
    ]
  },
  {
    "id": "de",
    "name": "Delaware",
    "abbreviation": "DE",
    "fips": "10",
    "bounds": [
      [
        -75.79,
        38.451
      ],
      [
        -75.051,
        39.839
      ]
    ],
    "center": [
      -75.42,
      39.145
    ]
  },
  {
    "id": "dc",
    "name": "District of Columbia",
    "abbreviation": "DC",
    "fips": "11",
    "bounds": [
      [
        -77.118,
        38.792
      ],
      [
        -76.91,
        38.994
      ]
    ],
    "center": [
      -77.014,
      38.893
    ]
  },
  {
    "id": "fl",
    "name": "Florida",
    "abbreviation": "FL",
    "fips": "12",
    "bounds": [
      [
        -87.635,
        24.515
      ],
      [
        -80.033,
        31.001
      ]
    ],
    "center": [
      -83.834,
      27.758
    ]
  },
  {
    "id": "ga",
    "name": "Georgia",
    "abbreviation": "GA",
    "fips": "13",
    "bounds": [
      [
        -85.607,
        30.359
      ],
      [
        -80.844,
        35.001
      ]
    ],
    "center": [
      -83.225,
      32.68
    ]
  },
  {
    "id": "hi",
    "name": "Hawaii",
    "abbreviation": "HI",
    "fips": "15",
    "bounds": [
      [
        -160.25,
        18.917
      ],
      [
        -154.808,
        22.232
      ]
    ],
    "center": [
      -157.529,
      20.575
    ]
  },
  {
    "id": "id",
    "name": "Idaho",
    "abbreviation": "ID",
    "fips": "16",
    "bounds": [
      [
        -117.243,
        41.988
      ],
      [
        -111.044,
        49.001
      ]
    ],
    "center": [
      -114.143,
      45.494
    ]
  },
  {
    "id": "il",
    "name": "Illinois",
    "abbreviation": "IL",
    "fips": "17",
    "bounds": [
      [
        -91.515,
        36.97
      ],
      [
        -87.495,
        42.509
      ]
    ],
    "center": [
      -89.505,
      39.74
    ]
  },
  {
    "id": "in",
    "name": "Indiana",
    "abbreviation": "IN",
    "fips": "18",
    "bounds": [
      [
        -88.098,
        37.772
      ],
      [
        -84.785,
        41.761
      ]
    ],
    "center": [
      -86.441,
      39.766
    ]
  },
  {
    "id": "ia",
    "name": "Iowa",
    "abbreviation": "IA",
    "fips": "19",
    "bounds": [
      [
        -96.633,
        40.378
      ],
      [
        -90.14,
        43.5
      ]
    ],
    "center": [
      -93.387,
      41.939
    ]
  },
  {
    "id": "ks",
    "name": "Kansas",
    "abbreviation": "KS",
    "fips": "20",
    "bounds": [
      [
        -102.053,
        36.993
      ],
      [
        -94.591,
        40.003
      ]
    ],
    "center": [
      -98.322,
      38.498
    ]
  },
  {
    "id": "ky",
    "name": "Kentucky",
    "abbreviation": "KY",
    "fips": "21",
    "bounds": [
      [
        -89.573,
        36.497
      ],
      [
        -81.967,
        39.146
      ]
    ],
    "center": [
      -85.77,
      37.822
    ]
  },
  {
    "id": "la",
    "name": "Louisiana",
    "abbreviation": "LA",
    "fips": "22",
    "bounds": [
      [
        -94.042,
        28.93
      ],
      [
        -88.816,
        33.02
      ]
    ],
    "center": [
      -91.429,
      30.975
    ]
  },
  {
    "id": "me",
    "name": "Maine",
    "abbreviation": "ME",
    "fips": "23",
    "bounds": [
      [
        -71.084,
        43.059
      ],
      [
        -66.982,
        47.46
      ]
    ],
    "center": [
      -69.033,
      45.259
    ]
  },
  {
    "id": "md",
    "name": "Maryland",
    "abbreviation": "MD",
    "fips": "24",
    "bounds": [
      [
        -79.487,
        37.917
      ],
      [
        -75.051,
        39.723
      ]
    ],
    "center": [
      -77.269,
      38.82
    ]
  },
  {
    "id": "ma",
    "name": "Massachusetts",
    "abbreviation": "MA",
    "fips": "25",
    "bounds": [
      [
        -73.507,
        41.239
      ],
      [
        -69.929,
        42.887
      ]
    ],
    "center": [
      -71.718,
      42.063
    ]
  },
  {
    "id": "mi",
    "name": "Michigan",
    "abbreviation": "MI",
    "fips": "26",
    "bounds": [
      [
        -90.416,
        41.696
      ],
      [
        -82.416,
        48.191
      ]
    ],
    "center": [
      -86.416,
      44.943
    ]
  },
  {
    "id": "mn",
    "name": "Minnesota",
    "abbreviation": "MN",
    "fips": "27",
    "bounds": [
      [
        -97.24,
        43.499
      ],
      [
        -89.49,
        49.385
      ]
    ],
    "center": [
      -93.365,
      46.442
    ]
  },
  {
    "id": "ms",
    "name": "Mississippi",
    "abbreviation": "MS",
    "fips": "28",
    "bounds": [
      [
        -91.644,
        30.18
      ],
      [
        -88.098,
        34.995
      ]
    ],
    "center": [
      -89.871,
      32.588
    ]
  },
  {
    "id": "mo",
    "name": "Missouri",
    "abbreviation": "MO",
    "fips": "29",
    "bounds": [
      [
        -95.768,
        35.995
      ],
      [
        -89.099,
        40.614
      ]
    ],
    "center": [
      -92.434,
      38.305
    ]
  },
  {
    "id": "mt",
    "name": "Montana",
    "abbreviation": "MT",
    "fips": "30",
    "bounds": [
      [
        -116.051,
        44.358
      ],
      [
        -104.041,
        49.002
      ]
    ],
    "center": [
      -110.046,
      46.68
    ]
  },
  {
    "id": "ne",
    "name": "Nebraska",
    "abbreviation": "NE",
    "fips": "31",
    "bounds": [
      [
        -104.052,
        40
      ],
      [
        -95.309,
        43.001
      ]
    ],
    "center": [
      -99.68,
      41.501
    ]
  },
  {
    "id": "nv",
    "name": "Nevada",
    "abbreviation": "NV",
    "fips": "32",
    "bounds": [
      [
        -120.007,
        35.001
      ],
      [
        -114.041,
        42.002
      ]
    ],
    "center": [
      -117.024,
      38.502
    ]
  },
  {
    "id": "nh",
    "name": "New Hampshire",
    "abbreviation": "NH",
    "fips": "33",
    "bounds": [
      [
        -72.556,
        42.697
      ],
      [
        -70.704,
        45.306
      ]
    ],
    "center": [
      -71.63,
      44.001
    ]
  },
  {
    "id": "nj",
    "name": "New Jersey",
    "abbreviation": "NJ",
    "fips": "34",
    "bounds": [
      [
        -75.56,
        38.928
      ],
      [
        -73.895,
        41.358
      ]
    ],
    "center": [
      -74.728,
      40.143
    ]
  },
  {
    "id": "nm",
    "name": "New Mexico",
    "abbreviation": "NM",
    "fips": "35",
    "bounds": [
      [
        -109.048,
        31.332
      ],
      [
        -103,
        37
      ]
    ],
    "center": [
      -106.024,
      34.166
    ]
  },
  {
    "id": "ny",
    "name": "New York",
    "abbreviation": "NY",
    "fips": "36",
    "bounds": [
      [
        -79.763,
        40.502
      ],
      [
        -71.856,
        45.016
      ]
    ],
    "center": [
      -75.81,
      42.759
    ]
  },
  {
    "id": "nc",
    "name": "North Carolina",
    "abbreviation": "NC",
    "fips": "37",
    "bounds": [
      [
        -84.322,
        33.851
      ],
      [
        -75.46,
        36.588
      ]
    ],
    "center": [
      -79.891,
      35.22
    ]
  },
  {
    "id": "nd",
    "name": "North Dakota",
    "abbreviation": "ND",
    "fips": "38",
    "bounds": [
      [
        -104.049,
        45.935
      ],
      [
        -96.558,
        49.001
      ]
    ],
    "center": [
      -100.303,
      47.468
    ]
  },
  {
    "id": "oh",
    "name": "Ohio",
    "abbreviation": "OH",
    "fips": "39",
    "bounds": [
      [
        -84.821,
        38.405
      ],
      [
        -80.521,
        41.978
      ]
    ],
    "center": [
      -82.671,
      40.191
    ]
  },
  {
    "id": "ok",
    "name": "Oklahoma",
    "abbreviation": "OK",
    "fips": "40",
    "bounds": [
      [
        -103.004,
        33.617
      ],
      [
        -94.433,
        37.002
      ]
    ],
    "center": [
      -98.718,
      35.309
    ]
  },
  {
    "id": "or",
    "name": "Oregon",
    "abbreviation": "OR",
    "fips": "41",
    "bounds": [
      [
        -124.554,
        41.992
      ],
      [
        -116.464,
        46.268
      ]
    ],
    "center": [
      -120.509,
      44.13
    ]
  },
  {
    "id": "pa",
    "name": "Pennsylvania",
    "abbreviation": "PA",
    "fips": "42",
    "bounds": [
      [
        -80.521,
        39.72
      ],
      [
        -74.695,
        42.27
      ]
    ],
    "center": [
      -77.608,
      40.995
    ]
  },
  {
    "id": "pr",
    "name": "Puerto Rico",
    "abbreviation": "PR",
    "fips": "72",
    "bounds": [
      [
        -67.94,
        17.912
      ],
      [
        -65.223,
        18.516
      ]
    ],
    "center": [
      -66.582,
      18.214
    ]
  },
  {
    "id": "ri",
    "name": "Rhode Island",
    "abbreviation": "RI",
    "fips": "44",
    "bounds": [
      [
        -71.86,
        41.151
      ],
      [
        -71.12,
        42.019
      ]
    ],
    "center": [
      -71.49,
      41.585
    ]
  },
  {
    "id": "sc",
    "name": "South Carolina",
    "abbreviation": "SC",
    "fips": "45",
    "bounds": [
      [
        -83.349,
        32.034
      ],
      [
        -78.539,
        35.215
      ]
    ],
    "center": [
      -80.944,
      33.625
    ]
  },
  {
    "id": "sd",
    "name": "South Dakota",
    "abbreviation": "SD",
    "fips": "46",
    "bounds": [
      [
        -104.059,
        42.485
      ],
      [
        -96.436,
        45.945
      ]
    ],
    "center": [
      -100.247,
      44.215
    ]
  },
  {
    "id": "tn",
    "name": "Tennessee",
    "abbreviation": "TN",
    "fips": "47",
    "bounds": [
      [
        -90.309,
        34.983
      ],
      [
        -81.648,
        36.678
      ]
    ],
    "center": [
      -85.978,
      35.83
    ]
  },
  {
    "id": "tx",
    "name": "Texas",
    "abbreviation": "TX",
    "fips": "48",
    "bounds": [
      [
        -106.647,
        25.84
      ],
      [
        -93.518,
        36.501
      ]
    ],
    "center": [
      -100.082,
      31.17
    ]
  },
  {
    "id": "ut",
    "name": "Utah",
    "abbreviation": "UT",
    "fips": "49",
    "bounds": [
      [
        -114.052,
        36.998
      ],
      [
        -109.041,
        42.002
      ]
    ],
    "center": [
      -111.547,
      39.5
    ]
  },
  {
    "id": "vt",
    "name": "Vermont",
    "abbreviation": "VT",
    "fips": "50",
    "bounds": [
      [
        -73.439,
        42.727
      ],
      [
        -71.494,
        45.016
      ]
    ],
    "center": [
      -72.466,
      43.871
    ]
  },
  {
    "id": "va",
    "name": "Virginia",
    "abbreviation": "VA",
    "fips": "51",
    "bounds": [
      [
        -83.676,
        36.541
      ],
      [
        -75.241,
        39.466
      ]
    ],
    "center": [
      -79.458,
      38.003
    ]
  },
  {
    "id": "wa",
    "name": "Washington",
    "abbreviation": "WA",
    "fips": "53",
    "bounds": [
      [
        -124.734,
        45.544
      ],
      [
        -116.916,
        49.002
      ]
    ],
    "center": [
      -120.825,
      47.273
    ]
  },
  {
    "id": "wv",
    "name": "West Virginia",
    "abbreviation": "WV",
    "fips": "54",
    "bounds": [
      [
        -82.638,
        37.202
      ],
      [
        -77.721,
        40.639
      ]
    ],
    "center": [
      -80.18,
      38.92
    ]
  },
  {
    "id": "wi",
    "name": "Wisconsin",
    "abbreviation": "WI",
    "fips": "55",
    "bounds": [
      [
        -92.889,
        42.492
      ],
      [
        -86.824,
        47.077
      ]
    ],
    "center": [
      -89.856,
      44.784
    ]
  },
  {
    "id": "wy",
    "name": "Wyoming",
    "abbreviation": "WY",
    "fips": "56",
    "bounds": [
      [
        -111.058,
        40.995
      ],
      [
        -104.052,
        45.006
      ]
    ],
    "center": [
      -107.555,
      43.001
    ]
  }
];
