import type { LayerDefinition } from "@/lib/types";
import { WA_SOURCES } from "./sources";

/**
 * Full layer registry for Washington. This is the single place that maps a
 * layer id to its category, styling, source, and API endpoint — the map,
 * the layer control panel, and the legend all read from this list rather
 * than hard-coding Washington specifics.
 */
export const WA_LAYERS: LayerDefinition[] = [
  // ---------------------------------------------------------------- POWER
  {
    id: "transmission-lines-high",
    name: "High-Voltage Transmission Lines (≥230 kV)",
    shortName: "Transmission (High)",
    category: "power",
    geometryType: "line",
    source: WA_SOURCES.bpaTransmission,
    confidence: "fact",
    description: "Bonneville Power Administration high-voltage transmission line geometry and voltage class.",
    defaultVisible: true,
    endpoint: "/api/gis/transmission-lines-high",
    color: "#ff5470",
    legend: [{ label: "230 kV and above", color: "#ff5470", swatch: "line", lineWidth: 3 }],
  },
  {
    id: "transmission-lines-low",
    name: "Low-Voltage Transmission Lines (<230 kV)",
    shortName: "Transmission (Low)",
    category: "power",
    geometryType: "line",
    source: WA_SOURCES.bpaTransmission,
    confidence: "fact",
    description: "Bonneville Power Administration high-voltage transmission line geometry and voltage class.",
    defaultVisible: true,
    endpoint: "/api/gis/transmission-lines-low",
    color: "#f2c94c",
    legend: [{ label: "Below 230 kV / unknown", color: "#f2c94c", swatch: "line", lineWidth: 1.8 }],
  },
  {
    id: "utility-territories",
    name: "Electric Utility Service Areas",
    shortName: "Utility Territories",
    category: "power",
    geometryType: "polygon",
    source: WA_SOURCES.waUtilityTerritories,
    confidence: "proxy",
    description:
      "Informational utility service area boundaries compiled by WA Ecology/UTC. Not an official service determination.",
    defaultVisible: false,
    endpoint: "/api/gis/utility-territories",
    color: "#5b7a9d",
    legend: [{ label: "Utility territory boundary", color: "#5b7a9d", swatch: "fill" }],
  },
  {
    id: "electric-substations",
    name: "Electric Substations",
    shortName: "Substations",
    category: "power",
    geometryType: "point",
    source: WA_SOURCES.hifldSubstations,
    confidence: "fact",
    description:
      "HIFLD electric substation locations (nationwide legacy extract, static — see source note), split by transmission voltage tier. Distance to the nearest substation is a proxy for interconnection access, not confirmed available capacity.",
    defaultVisible: true,
    endpoint: "/api/gis/electric-substations",
    legend: [
      { label: "345 kV+", color: "#ff5470", swatch: "circle" },
      { label: "115–344 kV", color: "#f2b93b", swatch: "circle" },
      { label: "< 115 kV / unknown", color: "#8fa3bf", swatch: "circle" },
    ],
  },

  // ---------------------------------------------------------------- WATER
  {
    id: "hydrography-rivers",
    name: "Rivers & Streams",
    category: "water",
    geometryType: "line",
    source: WA_SOURCES.usgsNhdFlowline,
    confidence: "fact",
    description: "USGS National Hydrography Dataset flowlines (small-scale).",
    defaultVisible: true,
    endpoint: "/api/gis/hydrography-rivers",
    color: "#3ba9f2",
    legend: [{ label: "River / stream", color: "#3ba9f2", swatch: "line", lineWidth: 1.5 }],
  },
  {
    id: "hydrography-waterbodies",
    name: "Water Bodies (Lakes & Reservoirs)",
    shortName: "Water Bodies",
    category: "water",
    geometryType: "polygon",
    source: WA_SOURCES.usgsNhdWaterbody,
    confidence: "fact",
    description: "USGS National Hydrography Dataset waterbody polygons (small-scale).",
    defaultVisible: true,
    endpoint: "/api/gis/hydrography-waterbodies",
    color: "#1f6fa8",
    legend: [{ label: "Lake / reservoir", color: "#1f6fa8", swatch: "fill" }],
  },
  {
    id: "usgs-gauges",
    name: "USGS Streamflow Gauges",
    category: "water",
    geometryType: "point",
    source: WA_SOURCES.usgsNwisGauges,
    confidence: "fact",
    description: "Active USGS surface-water monitoring stations with current discharge readings.",
    defaultVisible: false,
    endpoint: "/api/gis/usgs-gauges",
    color: "#63d4ff",
    legend: [{ label: "Active gauge", color: "#63d4ff", swatch: "circle" }],
  },
  {
    id: "water-diversions",
    name: "Water Right Diversions",
    category: "water",
    geometryType: "point",
    source: WA_SOURCES.waWaterDiversions,
    confidence: "fact",
    description: "Permitted water right diversion points (WA Dept. of Ecology).",
    defaultVisible: false,
    endpoint: "/api/gis/water-diversions",
    color: "#2ee6c8",
    legend: [{ label: "Water right diversion", color: "#2ee6c8", swatch: "circle" }],
  },
  {
    id: "drought-areas",
    name: "Drought Declaration Areas",
    category: "water",
    geometryType: "polygon",
    source: WA_SOURCES.waDroughtAreas,
    confidence: "fact",
    description: "State-declared drought areas (WA Dept. of Ecology).",
    defaultVisible: false,
    endpoint: "/api/gis/drought-areas",
    color: "#c9722f",
    legend: [{ label: "Drought-declared area", color: "#c9722f", swatch: "fill" }],
  },

  // --------------------------------------------------------- CONNECTIVITY
  {
    id: "colocation-facilities",
    name: "Colocation / Interconnection Facilities",
    shortName: "Colo Facilities",
    category: "connectivity",
    geometryType: "point",
    source: WA_SOURCES.peeringDb,
    confidence: "fact",
    description:
      "PeeringDB-listed carrier hotels and colocation facilities — a proxy for interconnection density, not a survey of long-haul fiber routes.",
    defaultVisible: true,
    endpoint: "/api/gis/colocation-facilities",
    color: "#9b6ef2",
    legend: [{ label: "Colocation / IX facility", color: "#9b6ef2", swatch: "circle" }],
  },

  // ----------------------------------------------------------- ENVIRONMENT
  {
    id: "flood-zones",
    name: "FEMA Flood Hazard Zones",
    shortName: "Flood Zones",
    category: "environment",
    geometryType: "polygon",
    source: WA_SOURCES.femaNfhl,
    confidence: "fact",
    description: "Effective FEMA National Flood Hazard Layer zones, where mapped.",
    defaultVisible: false,
    endpoint: "/api/gis/flood-zones",
    color: "#e0524a",
    legend: [
      { label: "High risk (A/AE/V zones)", color: "#e0524a", swatch: "fill" },
      { label: "Moderate/minimal (X/other)", color: "#e0a84a", swatch: "fill" },
    ],
  },

  {
    id: "forest-cover",
    name: "Forest / Tree Canopy",
    shortName: "Forests",
    category: "environment",
    geometryType: "raster",
    source: WA_SOURCES.cartoForestCover,
    confidence: "proxy",
    description:
      "Visual forest/wood land-cover polygons from the CARTO basemap's OpenStreetMap-derived landcover layer. Optimized for clear map reading; not an authoritative forestry inventory.",
    defaultVisible: false,
    color: "#4f7f50",
    legend: [{ label: "Tree canopy / forest cover", color: "#4f7f50", swatch: "fill" }],
  },
  {
    id: "terrain-hillshade",
    name: "Terrain / Mountains",
    shortName: "Terrain",
    category: "environment",
    geometryType: "raster",
    source: WA_SOURCES.usgsShadedRelief,
    confidence: "fact",
    description:
      "USGS The National Map cached shaded relief, derived from 3DEP at large and medium scales. Rendered as a subtle flat overlay for mountain and terrain context.",
    defaultVisible: false,
    color: "#8d8a82",
    legend: [{ label: "Shaded terrain relief", color: "#8d8a82", swatch: "fill" }],
  },
  {
    id: "state-highways",
    name: "State Highways",
    category: "environment",
    geometryType: "line",
    source: WA_SOURCES.wsdotHighways,
    confidence: "fact",
    description: "WSDOT state route centerlines, classified by federal functional class (interstate/arterial/etc).",
    defaultVisible: false,
    endpoint: "/api/gis/state-highways",
    color: "#c9d3e0",
    legend: [{ label: "State highway / route", color: "#c9d3e0", swatch: "line", lineWidth: 1.5 }],
  },

  // -------------------------------------------------------------- COMMUNITY
  {
    id: "population-tracts",
    name: "Census Tract Boundaries",
    category: "community",
    geometryType: "polygon",
    source: WA_SOURCES.censusTiger,
    confidence: "fact",
    description: "US Census tract boundaries, used for population-proximity estimates.",
    defaultVisible: false,
    endpoint: "/api/gis/population-tracts",
    color: "#6b7f99",
    legend: [{ label: "Census tract boundary", color: "#6b7f99", swatch: "line" }],
  },
  {
    id: "population-density",
    name: "County Population Density",
    shortName: "Pop. Density",
    category: "community",
    geometryType: "polygon",
    source: WA_SOURCES.censusCountyDensity,
    confidence: "estimated",
    description:
      "County-level population density (people per sq mi), combining Census Population Estimates with Gazetteer land area, shown as a quiet background wash (no highlight below 25/sq mi). Denser counties tend to carry more existing residential/commercial load on the local grid, competing with a new large facility for available transmission and substation headroom — the same amber-to-red \"demand pressure\" scale also appears as a soft glow along transmission lines that run through these counties.",
    defaultVisible: false,
    endpoint: "/api/gis/population-density",
    legend: [
      { label: "< 25 / sq mi — no highlight (rural)", color: "#2a3342", swatch: "fill" },
      { label: "25–150 / sq mi (suburban)", color: "#f2b93b", swatch: "fill" },
      { label: "150–1,000 / sq mi (urban)", color: "#f2703b", swatch: "fill" },
      { label: "1,000+ / sq mi (dense urban)", color: "#ff5470", swatch: "fill" },
    ],
  },

  // ----------------------------------------------------- EXISTING INFRA
  {
    id: "power-plants",
    name: "Power Generation Facilities",
    shortName: "Generation",
    category: "existing_infrastructure",
    geometryType: "point",
    source: WA_SOURCES.eia,
    confidence: "unknown",
    description:
      "Nearby generating facilities from EIA. Requires a server-side EIA_API_KEY — shown as unavailable until configured.",
    defaultVisible: true,
    endpoint: "/api/gis/power-plants",
    color: "#f2b93b",
    legend: [{ label: "Generating facility", color: "#f2b93b", swatch: "circle" }],
  },
  {
    id: "data-centers",
    name: "Known Data Center Campuses",
    shortName: "Data Centers",
    category: "existing_infrastructure",
    geometryType: "point",
    source: WA_SOURCES.curatedDataCenters,
    confidence: "proxy",
    description: "Hand-curated, illustrative list of publicly reported WA data center campuses. Not exhaustive.",
    defaultVisible: true,
    endpoint: "/api/gis/data-centers",
    color: "#8fa3bf",
    legend: [{ label: "Existing data center campus", color: "#8fa3bf", swatch: "circle" }],
  },
];

export function getWaLayer(id: string): LayerDefinition | undefined {
  return WA_LAYERS.find((l) => l.id === id);
}
