import type { SourceMeta } from "@/lib/types";
import { NATIONAL_SOURCES } from "@/lib/gis/nationalSources";

/**
 * Canonical source metadata for every Washington dataset the platform uses.
 * Referenced by both layer definitions (for the legend/provenance UI) and the
 * analysis engine (for per-metric attribution).
 */
export const WA_SOURCES = {
  bpaTransmission: {
    id: "bpa-transmission",
    name: "Bonneville Power Administration — Transmission Lines",
    url: "https://services3.arcgis.com/Iz3chmSt4P7oOoZy/arcgis/rest/services/BPA_TransmissionLines_View/FeatureServer/0",
    license: "Public (BPA open data)",
    refreshFrequency: "Live ArcGIS FeatureServer (BPA-maintained)",
    methodology: "Queried live by bounding box; voltage from the VoltageMeas attribute.",
  },
  waUtilityTerritories: {
    id: "wa-utility-territories",
    name: "WA Dept. of Ecology — Electric Utility Service Areas",
    url: "https://gis.ecology.wa.gov/serverext/rest/services/CPR/CPR/FeatureServer/0",
    license: "Public (WA Ecology open data)",
    refreshFrequency: "Live ArcGIS FeatureServer",
    methodology: "Point-in-polygon lookup against utility-provided/UTC service area boundaries.",
  },
  hifldSubstations: NATIONAL_SOURCES.hifldSubstations,
  waWaterDiversions: {
    id: "wa-water-diversions",
    name: "WA Dept. of Ecology — Water Right Diversions (NHD-located)",
    url: "https://gis.ecology.wa.gov/serverext/rest/services/Authoritative/WR/MapServer/1",
    license: "Public (WA Ecology open data)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "Point features representing permitted water right diversion locations.",
  },
  waInstreamFlow: {
    id: "wa-instream-flow",
    name: "WA Dept. of Ecology — Instream Flow Rules",
    url: "https://gis.ecology.wa.gov/serverext/rest/services/Authoritative/WR/MapServer/2",
    license: "Public (WA Ecology open data)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "Regulatory instream flow rule geographies.",
  },
  waDroughtAreas: {
    id: "wa-drought-areas",
    name: "WA Dept. of Ecology — Drought Areas",
    url: "https://gis.ecology.wa.gov/serverext/rest/services/Authoritative/WR/MapServer/3",
    license: "Public (WA Ecology open data)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "State-declared drought area geographies.",
  },
  usgsNhdFlowline: {
    id: "usgs-nhd-flowline",
    name: "USGS National Hydrography Dataset — Flowlines (small scale)",
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/4",
    license: "Public domain (USGS)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "Small-scale river/stream centerlines queried by bounding box.",
  },
  usgsNhdWaterbody: {
    id: "usgs-nhd-waterbody",
    name: "USGS National Hydrography Dataset — Waterbodies (small scale)",
    url: "https://hydro.nationalmap.gov/arcgis/rest/services/nhd/MapServer/10",
    license: "Public domain (USGS)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "Small-scale lake/reservoir polygons queried by bounding box.",
  },
  usgsNwisGauges: {
    id: "usgs-nwis-gauges",
    name: "USGS NWIS — Active Streamflow Gauges",
    url: "https://waterservices.usgs.gov/nwis/iv/",
    license: "Public domain (USGS)",
    refreshFrequency: "Near real-time instantaneous values",
    methodology: "Active surface-water gauge sites with current discharge reading, statewide, filtered client-side by radius.",
  },
  usgsEpqs: {
    id: "usgs-epqs",
    name: "USGS Elevation Point Query Service",
    url: "https://epqs.nationalmap.gov/v1/json",
    license: "Public domain (USGS)",
    refreshFrequency: "Live point query",
    methodology: "3DEP-derived elevation at the queried point.",
  },
  femaNfhl: {
    id: "fema-nfhl",
    name: "FEMA National Flood Hazard Layer — Flood Hazard Zones",
    url: "https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28",
    license: "Public (FEMA)",
    refreshFrequency: "Live ArcGIS MapServer; coverage varies by county study status",
    methodology: "Effective FIRM flood zone polygon containing the point, where mapped.",
  },
  peeringDb: {
    id: "peeringdb-fac",
    name: "PeeringDB — Colocation / Interconnection Facilities",
    url: "https://www.peeringdb.com/api/fac",
    license: "PeeringDB (CC BY-SA-ish community data, see peeringdb.com/about)",
    refreshFrequency: "Live API, community-maintained",
    methodology: "Facility records self-reported by network operators; used as a proxy for interconnection-dense sites, not a survey of long-haul fiber routes.",
  },
  censusAcs: {
    id: "census-acs5",
    name: "US Census Bureau — ACS 5-Year Population Estimates",
    url: "https://api.census.gov/data/2022/acs/acs5",
    license: "Public domain (US Census Bureau)",
    refreshFrequency: "Annual (ACS 5-year release)",
    methodology: "Tract-level population, area-weighted against a 5-mile radius buffer.",
  },
  censusTiger: {
    id: "census-tigerweb",
    name: "US Census Bureau — TIGERweb Tract Boundaries",
    url: "https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/tigerWMS_Current/MapServer",
    license: "Public domain (US Census Bureau)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "Current tract boundaries queried by bounding box.",
  },
  censusCountyDensity: {
    id: "census-county-population-density",
    name: "US Census Bureau — County Population Density (PEP + Gazetteer)",
    url: "https://www2.census.gov/programs-surveys/popest/datasets/",
    license: "Public domain (US Census Bureau)",
    refreshFrequency: "Annual (Population Estimates Program vintage; land area from the Census Gazetteer)",
    methodology:
      "County population (Census Bureau Population Estimates Program, most recent published vintage) divided by land area (Census Gazetteer ALAND_SQMI) to give people per square mile, joined to live TIGERweb county boundaries by GEOID.",
  },
  eia: {
    id: "eia-v2",
    name: "US Energy Information Administration — Open Data API v2",
    url: "https://api.eia.gov/v2",
    license: "Public domain (EIA)",
    refreshFrequency: "Varies by dataset (generally monthly/annual)",
    methodology: "Server-side query using an EIA API key; requires EIA_API_KEY to be configured.",
  },
  fccBroadband: NATIONAL_SOURCES.fccBroadband,
  censusBroadband: NATIONAL_SOURCES.censusBroadband,
  cartoForestCover: {
    id: "carto-osm-forest-cover",
    name: "CARTO Vector Basemap — OSM Landcover (wood)",
    url: "https://tiles.basemaps.cartocdn.com/vector/carto.streets/v1/tiles.json",
    license: "CARTO basemap / OpenStreetMap-derived data (ODbL attribution applies)",
    refreshFrequency: "Basemap provider refresh cycle",
    methodology: "Visual forest overlay using the basemap vector landcover layer filtered to the 'wood' class. This is a cartographic forest proxy, not an authoritative forestry inventory.",
  },
  usgsShadedRelief: {
    id: "usgs-shaded-relief",
    name: "USGS The National Map — Shaded Relief",
    url: "https://basemap.nationalmap.gov/arcgis/rest/services/USGSShadedReliefOnly/MapServer",
    license: "Public domain (USGS)",
    refreshFrequency: "USGS cached basemap service",
    methodology: "Cached shaded-relief tiles derived from 3DEP at large/medium scales, displayed as a low-opacity terrain context layer with no 3D extrusion.",
  },
  wsdotHighways: {
    id: "wsdot-functional-class",
    name: "WSDOT — State Highway Functional Classification",
    url: "https://data.wsdot.wa.gov/arcgis/rest/services/FunctionalClass/WSDOTFunctionalClassData/MapServer/0",
    license: "Public (WSDOT open data)",
    refreshFrequency: "Live ArcGIS MapServer",
    methodology: "State route centerlines with federal functional class; used for road-access context and nearest-major-road distance (functional class 1–3 treated as major).",
  },
  curatedDataCenters: {
    id: "curated-wa-datacenters",
    name: "Curated Known Data Center Campuses (Washington)",
    url: "",
    license: "Compiled from public reporting; not an authoritative registry",
    refreshFrequency: "Manually maintained",
    methodology: "Hand-curated illustrative list of publicly reported major WA data center campuses. NOT exhaustive and NOT independently verified against parcel/operator records.",
  },
} satisfies Record<string, SourceMeta>;
