import type { LayerDefinition } from "@/lib/types";
import { MO_SOURCES } from "./sources";

/**
 * Missouri live layer registry. National sources cover the common layers while
 * Missouri DNR contributes groundwater-observation and public-water-source
 * infrastructure. Water-use reporting is intentionally not represented as a
 * point-level "water rights" layer because Missouri follows riparian principles
 * and the Major Water User program is a reporting program, not a capacity map.
 */
export const MO_LAYERS: LayerDefinition[] = [
  {
    id: "transmission-lines",
    name: "Electric Power Transmission Lines",
    shortName: "Transmission",
    category: "power",
    geometryType: "line",
    source: MO_SOURCES.hifldTransmission,
    confidence: "fact",
    description:
      "HIFLD transmission line geometry with voltage and owner/operator attributes where published. Missouri is a major grid crossroads; line proximity does not establish available MW or substation headroom.",
    defaultVisible: true,
    endpoint: "/api/gis/transmission-lines",
    legend: [
      { label: "500 kV+", color: "#ff5470", swatch: "line", lineWidth: 3 },
      { label: "230–499 kV", color: "#f2b93b", swatch: "line", lineWidth: 2.5 },
      { label: "115–229 kV", color: "#f2d98b", swatch: "line", lineWidth: 2 },
      { label: "< 115 kV / unknown", color: "#8fa3bf", swatch: "line", lineWidth: 1.5 },
    ],
  },
  {
    id: "utility-territories",
    name: "Electric Utility Retail Service Territories",
    shortName: "Utility Territories",
    category: "power",
    geometryType: "polygon",
    source: MO_SOURCES.hifldUtilityTerritories,
    confidence: "proxy",
    description:
      "Static HIFLD retail service territory polygons for map screening. Missouri PSC's Utility Locator should be used to confirm the serving utility for a specific property.",
    defaultVisible: false,
    endpoint: "/api/gis/utility-territories",
    color: "#5b7a9d",
    legend: [{ label: "Utility territory boundary", color: "#5b7a9d", swatch: "fill" }],
  },
  {
    id: "electric-substations",
    name: "Electric Substations",
    shortName: "Substations",
    category: "power",
    geometryType: "point",
    source: MO_SOURCES.hifldSubstations,
    confidence: "fact",
    description:
      "HIFLD electric substation locations (nationwide legacy extract, static — see source note), split by transmission voltage tier. Distance to the nearest substation is a proxy for interconnection access, not confirmed available capacity.",
    defaultVisible: true,
    endpoint: "/api/gis/electric-substations",
    legend: [
      { label: "345 kV+", color: "#ff5470", swatch: "circle" },
      { label: "115–344 kV", color: "#f2b93b", swatch: "circle" },
      { label: "< 115 kV / unknown", color: "#8fa3bf", swatch: "circle" },
    ],
  },
  {
    id: "hydrography-rivers",
    name: "Rivers & Streams",
    category: "water",
    geometryType: "line",
    source: MO_SOURCES.usgsNhdFlowline,
    confidence: "fact",
    description:
      "USGS National Hydrography Dataset flowlines, including the Missouri, Mississippi, and Osage river systems. Proximity is not water-use authorization.",
    defaultVisible: true,
    endpoint: "/api/gis/hydrography-rivers",
    color: "#3ba9f2",
    legend: [{ label: "River / stream", color: "#3ba9f2", swatch: "line", lineWidth: 1.5 }],
  },
  {
    id: "hydrography-waterbodies",
    name: "Water Bodies (Lakes & Reservoirs)",
    shortName: "Water Bodies",
    category: "water",
    geometryType: "polygon",
    source: MO_SOURCES.usgsNhdWaterbody,
    confidence: "fact",
    description:
      "USGS National Hydrography Dataset lake/reservoir polygons, including major Missouri reservoirs. Proximity does not imply industrial availability.",
    defaultVisible: true,
    endpoint: "/api/gis/hydrography-waterbodies",
    color: "#1f6fa8",
    legend: [{ label: "Lake / reservoir", color: "#1f6fa8", swatch: "fill" }],
  },
  {
    id: "usgs-gauges",
    name: "USGS Streamflow Gauges",
    category: "water",
    geometryType: "point",
    source: MO_SOURCES.usgsNwisGauges,
    confidence: "fact",
    description: "Active USGS surface-water monitoring stations with current discharge readings.",
    defaultVisible: false,
    endpoint: "/api/gis/usgs-gauges",
    color: "#63d4ff",
    legend: [{ label: "Active gauge", color: "#63d4ff", swatch: "circle" }],
  },
  {
    id: "drought-areas",
    name: "U.S. Drought Monitor — Current Conditions",
    shortName: "Drought",
    category: "water",
    geometryType: "polygon",
    source: MO_SOURCES.usDroughtMonitor,
    confidence: "fact",
    description:
      "Current weekly drought classification (D0 abnormally dry through D4 exceptional drought), released by NDMC/NOAA/USDA.",
    defaultVisible: false,
    endpoint: "/api/gis/drought-areas",
    color: "#c9722f",
    legend: [
      { label: "D0 Abnormally dry", color: "#f2d98b", swatch: "fill" },
      { label: "D1–D2 Moderate–severe", color: "#e0a84a", swatch: "fill" },
      { label: "D3–D4 Extreme–exceptional", color: "#c9722f", swatch: "fill" },
    ],
  },
  {
    id: "groundwater-observation-wells",
    name: "Groundwater Observation Wells",
    shortName: "Groundwater Wells",
    category: "water",
    geometryType: "point",
    source: MO_SOURCES.groundwaterObservationWells,
    confidence: "fact",
    description:
      "Missouri DNR groundwater observation network. These monitoring locations provide groundwater context; they are not evidence of spare withdrawal capacity.",
    defaultVisible: false,
    endpoint: "/api/gis/groundwater-observation-wells",
    color: "#46b6a9",
    legend: [{ label: "Observation well", color: "#46b6a9", swatch: "circle" }],
  },
  {
    id: "public-water-sources",
    name: "Public Drinking Water Sources",
    shortName: "Public Water",
    category: "water",
    geometryType: "point",
    source: MO_SOURCES.publicDrinkingWaterWells,
    confidence: "fact",
    description:
      "Missouri DNR public drinking-water wells and surface intakes. This is infrastructure context only; industrial service, treatment capacity, and spare capacity must be confirmed with the utility.",
    defaultVisible: false,
    endpoint: "/api/gis/public-water-sources",
    color: "#3f8fc9",
    legend: [{ label: "Public water well / intake", color: "#3f8fc9", swatch: "circle" }],
  },
  {
    id: "colocation-facilities",
    name: "Colocation / Interconnection Facilities",
    shortName: "Colo Facilities",
    category: "connectivity",
    geometryType: "point",
    source: MO_SOURCES.peeringDb,
    confidence: "fact",
    description:
      "PeeringDB-listed carrier hotels and colocation facilities. Use as an interconnection-density proxy, not proof of long-haul or dark-fiber availability.",
    defaultVisible: true,
    endpoint: "/api/gis/colocation-facilities",
    color: "#9b6ef2",
    legend: [{ label: "Colocation / IX facility", color: "#9b6ef2", swatch: "circle" }],
  },
  {
    id: "flood-zones",
    name: "FEMA Flood Hazard Zones",
    shortName: "Flood Zones",
    category: "environment",
    geometryType: "polygon",
    source: MO_SOURCES.femaNfhl,
    confidence: "fact",
    description:
      "Effective FEMA flood hazard zones where mapped. Missouri and Mississippi River corridors are high-priority siting checks.",
    defaultVisible: false,
    endpoint: "/api/gis/flood-zones",
    color: "#e0524a",
    legend: [
      { label: "High risk (A/AE/V zones)", color: "#e0524a", swatch: "fill" },
      { label: "Moderate/minimal (X/other)", color: "#e0a84a", swatch: "fill" },
    ],
  },
  {
    id: "forest-cover",
    name: "Forest / Tree Canopy",
    shortName: "Forests",
    category: "environment",
    geometryType: "raster",
    source: MO_SOURCES.cartoForestCover,
    confidence: "proxy",
    description:
      "Visual OSM-derived forest/wood land-cover polygons from the CARTO basemap. Useful for map context, not an authoritative forestry inventory.",
    defaultVisible: false,
    color: "#4f7f50",
    legend: [{ label: "Tree canopy / forest cover", color: "#4f7f50", swatch: "fill" }],
  },
  {
    id: "terrain-hillshade",
    name: "Terrain / Elevation",
    shortName: "Terrain",
    category: "environment",
    geometryType: "raster",
    source: MO_SOURCES.usgsShadedRelief,
    confidence: "fact",
    description:
      "USGS 3DEP-derived shaded relief for terrain context. Southeast Missouri also warrants separate seismic review for New Madrid Seismic Zone exposure.",
    defaultVisible: false,
    color: "#8d8a82",
    legend: [{ label: "Shaded terrain relief", color: "#8d8a82", swatch: "fill" }],
  },
  {
    id: "population-tracts",
    name: "Census Tract Boundaries",
    category: "community",
    geometryType: "polygon",
    source: MO_SOURCES.censusTiger,
    confidence: "fact",
    description: "US Census tract boundaries, used for population-proximity estimates.",
    defaultVisible: false,
    endpoint: "/api/gis/population-tracts",
    color: "#6b7f99",
    legend: [{ label: "Census tract boundary", color: "#6b7f99", swatch: "line" }],
  },
  {
    id: "population-density",
    name: "County Population Density",
    shortName: "Pop. Density",
    category: "community",
    geometryType: "polygon",
    source: MO_SOURCES.censusCountyDensity,
    confidence: "estimated",
    description:
      "County-level population density (people per sq mi), combining Census Population Estimates with Gazetteer land area, shown as a quiet background wash (no highlight below 25/sq mi). Denser counties tend to carry more existing residential/commercial load on the local grid, competing with a new large facility for available transmission and substation headroom — the same amber-to-red \"demand pressure\" scale also appears as a soft glow along transmission lines that run through these counties.",
    defaultVisible: false,
    endpoint: "/api/gis/population-density",
    legend: [
      { label: "< 25 / sq mi — no highlight (rural)", color: "#2a3342", swatch: "fill" },
      { label: "25–150 / sq mi (suburban)", color: "#f2b93b", swatch: "fill" },
      { label: "150–1,000 / sq mi (urban)", color: "#f2703b", swatch: "fill" },
      { label: "1,000+ / sq mi (dense urban)", color: "#ff5470", swatch: "fill" },
    ],
  },
  {
    id: "power-plants",
    name: "Power Generation Facilities",
    shortName: "Generation",
    category: "existing_infrastructure",
    geometryType: "point",
    source: MO_SOURCES.eia,
    confidence: "unknown",
    description:
      "EIA-reported generating facilities. Display as NEARBY GENERATION only; nameplate capacity is not available power or grid headroom. Requires EIA_API_KEY.",
    defaultVisible: true,
    endpoint: "/api/gis/power-plants",
    color: "#f2b93b",
    legend: [{ label: "Generating facility", color: "#f2b93b", swatch: "circle" }],
  },
  {
    id: "data-centers",
    name: "Known / Announced Data Center Campuses",
    shortName: "Data Centers",
    category: "existing_infrastructure",
    geometryType: "point",
    source: MO_SOURCES.curatedDataCenters,
    confidence: "unknown",
    description:
      "The research identifies Kansas City, St. Louis, and Springfield as Missouri data-center markets, but no facility points are shown until coordinates are independently verified.",
    defaultVisible: true,
    endpoint: "/api/gis/data-centers",
    color: "#8fa3bf",
    legend: [{ label: "Verified data center campus", color: "#8fa3bf", swatch: "circle" }],
  },
];

export function getMoLayer(id: string): LayerDefinition | undefined {
  return MO_LAYERS.find((l) => l.id === id);
}
